model: "openai/gpt-oss-20b:free"
label:
  en_US: "FREE GPT-OSS 20B"
model_type: llm
features:
  - multi-tool-call
  - agent-thought
  - stream-tool-call
model_properties:
  mode: chat
  context_size: 131072
parameter_rules:
  - name: temperature
    use_template: temperature
  - name: max_tokens
    use_template: max_tokens
    default: 4096
pricing:
  input: "0.0"
  output: "0.0"
  unit: "0.000001"
  currency: USD
